packages:
  - packages/@xcambar/*
  - supabase/functions/*

ignoredBuiltDependencies:
  - '@parcel/watcher'
  - sharp
  - unix-dgram
  - unrs-resolver

onlyBuiltDependencies:
  - esbuild
  - netlify-cli
  - supabase
