CREATE TABLE "athlete_performance_profiles" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "athlete_performance_profiles_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"athlete_id" bigint NOT NULL,
	"speed_grade_0_5" real,
	"speed_grade_5_10" real,
	"speed_grade_10_15" real,
	"speed_grade_15_25" real,
	"speed_grade_over_25" real,
	"avg_pace_5k" real,
	"avg_pace_10k" real,
	"avg_pace_half_marathon" real,
	"avg_pace_marathon" real,
	"pace_degradation_per_km" real,
	"elevation_efficiency_factor" real,
	"total_activities" integer DEFAULT 0 NOT NULL,
	"total_distance_km" real DEFAULT 0 NOT NULL,
	"grade_coverage_flags" integer DEFAULT 0 NOT NULL,
	"computed_at" timestamp DEFAULT now(),
	"last_updated" timestamp DEFAULT now(),
	CONSTRAINT "athlete_performance_profiles_athlete_id_unique" UNIQUE("athlete_id")
);
--> statement-breakpoint
CREATE TABLE "gap_lookup" (
	"id" serial PRIMARY KEY NOT NULL,
	"grade_percent" real NOT NULL,
	"pace_adjustment_factor" real NOT NULL,
	CONSTRAINT "gap_lookup_grade_percent_unique" UNIQUE("grade_percent")
);